### ISSUE TITLE
TabControlEx - Selected Item is recreated when I switch tab

### ISSUE THREAD

**Issue by Xaalek** [ControlzEx/ControlzEx#159]
I'm using TabControlEx to handle tabs in my app.
Unfortunately, when I switch tab, the selected item is recreated.

[video.webm](https://user-images.githubusercontent.com/54487782/183418215-eb181ed5-5a13-4711-9215-df558385eb4f.webm)

The issue occurs when I apply an explicit style.

This code produces the issue.

```
<controlz:TabControlEx x:Name="tabContainer" 
                        Grid.Row="1"
                        Style="{StaticResource MaterialDesignTabControl}">
</controlz:TabControlEx>
```

This code not

```
<controlz:TabControlEx x:Name="tabContainer" 
                        Grid.Row="1">
</controlz:TabControlEx>
```

You can check the repo here: https://github.com/Xaalek/TestTabControl

## Environment

```
ControlzEx: 5.0.1
Win10 version: 21H2, build: 19044.1826
Microsoft Visual Studio Community 2022 (64 bits) - Version 17.1.1
Target Framework: .Net Framework 4.8
MahApps.Metro: 2.4.9
MaterialDesignColors: 2.0.6
MaterialDesignExtensions: 3.3.0
MaterialDesignThemes: 4.5.0
MaterialDesignThemes.MahApps: 0.2.2
Microsoft.Xaml.Behaviors.Wpf: 1.1.31 
```

**Comment by batzen** [comment]
That's because the style also sets the template.
The template has to be different to work correctly.
It has to expose a `Panel` with the name `PART_ItemsHolder` instead of a `ContentPresenter` with name `PART_SelectedContentHost` for content caching to work correctly and to prevent the default `TabControl` class from doing certain things.
To fix your issue you will have to copy the template from MatrialDesign and modify it accordingly.
