### ISSUE TITLE
ThemeManager doesn't work as described in wiki with runtime generated themes

### ISSUE THREAD

**Issue by will-scc** [ControlzEx/ControlzEx#177]
## Describe the bug
I have implemented usage of `ThemeManager` as described [in the Theming wiki page](https://github.com/ControlzEx/ControlzEx/blob/develop/Wiki/ThemeManager.md).

However, my application doesn't display any sort of colours/theme, nor does calling `ChangeTheme` from Light to Dark or visa-versa have any effect on the UI.

I have successfully used MahApps.Metro with theming in the past, which uses this, without issue... Is there some missing documentation about how to implement/use this? 

Sorry if I'm missing something obvious, but I can't see any documentation beyond what I've read that explains what more I need to do.

If I have to specify the colours in various controls styles, how should I reference them? I have tried things such as `MahApps.Colors.Highlight` and `ThemeGenerator.Colors.Highlight` but neither works.

## Steps to reproduce
Clone this demo (minimal) repo: https://github.com/will-scc/ThemingDemoApp

Build and run the application.

Note that by default no theming is applied to any controls. Clicking Light/Dark buttons, which call `ChangeTheme` have no effect.

## Environment

```
ControlzEx version: v6.0.0
Visual Studio: 2022 17.5.5
Target Framework: .NET 6
```

## Screenshots
![no theming displayed](https://github.com/ControlzEx/ControlzEx/assets/31592644/8a898694-cdb7-445b-8a97-9d54649ad5c4)

**Comment by batzen** [comment]
The ThemeManager in ControlzEx only provides the theming infrastructure and does not provide any built in theme or resources.

> Note that by default no theming is applied to any controls. Clicking Light/Dark buttons, which call ChangeTheme have no effect.

That's because ControlzEx does not provide any colors/resources/templates/styles.

> If I have to specify the colours in various controls styles, how should I reference them? I have tried things such as MahApps.Colors.Highlight and ThemeGenerator.Colors.Highlight but neither works.

You have to either use MahApps.Metro to get some styles/colors to influence or you have to build all that stuff on your own.

The only colors/resources provided by the runtime theme generator are the ones from https://github.com/ControlzEx/ControlzEx/blob/c6aadffb1b78c0784bf1333c667821477a72b279/src/ControlzEx/Theming/RuntimeThemeGenerator.cs#L129 and those only get supplied if the theme is really runtime generated.
Runtime generation of themes only happens if you have registered a `LibraryThemeProvider`.

To get an idea of what you'll have to do you can have a look at the following files/places:
https://github.com/ControlzEx/ControlzEx/blob/develop/src/ControlzEx.Showcase/Theming/ShowcaseLibraryThemeProvider.cs
https://github.com/ControlzEx/ControlzEx/blob/develop/src/ControlzEx.Showcase/Themes/Themes/GeneratorParameters.json
https://github.com/ControlzEx/ControlzEx/blob/develop/src/ControlzEx.Showcase/Themes/Themes/Theme.Template.xaml
https://github.com/ControlzEx/ControlzEx/blob/c6aadffb1b78c0784bf1333c667821477a72b279/src/ControlzEx.Showcase/ControlzEx.Showcase.csproj#L22
https://github.com/ControlzEx/ControlzEx/blob/c6aadffb1b78c0784bf1333c667821477a72b279/src/ControlzEx.Showcase/ControlzEx.Showcase.csproj#L26

I hope this helps.

**Comment by will-scc** [comment]
Thanks Batzen. I suspected something like that was the case, but couldn't quite pull across all the documentation to make sense of it.

If I wanted to use pre-defined resource dictionaries for my themes, how would I do that?

The documentation only goes as far as to say:
> You may also provide a custom ResourceDictionary with all the needed resources.
> 
> Get yourself a copy of the required Template
> MahApps.Metro: https://github.com/MahApps/MahApps.Metro/blob/main/src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
> Fluent.Ribbon: https://github.com/fluentribbon/Fluent.Ribbon/blob/master/Fluent.Ribbon/Themes/Themes/Theme.Template.xaml
> Replace all items surrounded by double curly braces {{ Content to Replace }}
> Remember to create all needed variants. E.g.: If you want to support light and dark themes you will need to implement both.

Once I have my template(s), how do I import those into ThemeManager so they can be used?

**Comment by batzen** [comment]
The easiest way to register your themes with the provider is to do it the way it's done by MahApps.Metro, Fluent.Ribbon or the showcase application here.

Assuming you want to use the template approach (Theme.Template.xaml + GeneratorParameters.json):
- Define your `LibraryThemeProvider` (call the base ctor with `true`)
- In your `Generic.xaml` use `<theming:MyLibraryThemeProvider x:Key="{x:Static theming:ShowcaseLibraryThemeProvider.DefaultInstance}" />`

Assuming you want to do everything manually:
- Use the above to ease registration
- Add code to your app startup or in the ctor of your `LibraryThemeProvider`
- Register your themes with your `LibraryThemeProvider`
- Add resources to your `LibraryTheme` instances by calling `AddResource` on them

**Comment by will-scc** [comment]
Thanks for the help @batzen, appreciate it. I'll give that ago.
