### ISSUE TITLE
The content of `WindowChromeWindow` will miss one pixel on the top side if `GlowColor` is used

### ISSUE THREAD

**Issue by Chaoses-Ib** [ControlzEx/ControlzEx#191]
## Describe the bug

If `GlowColor` is used, the content of a `WindowChromeWindow` will miss one pixel on the top side. For example, `GlowColor="Blue"` and `Background="Red"`:

![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/e0c9c623-5703-4b04-8824-a33a1140bbbc)

![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/0ce18173-d679-4832-93ff-aeaa100f6141)

This is caused by the `Grid.Margin` in the window template. When `GlowColor` is used the `Padding` will be set to `defaultContentPadding`, which is `Thickness(0, 1, 0, 0)`. #175 says it fixes the one pixel miss, however, here it becomes the reason for the one pixel miss instead. If I set the `Padding` to 0, the one pixel miss will disappear.

## Environment

```
ControlzEx version: v6.0.0
Windows build number: Win11 23H2 [Version 22631.3085] & Win10
Visual Studio: 2022 17.6.2
Target Framework: .Net Framework v4.8
```

**Comment by batzen** [comment]
Can't reproduce your issue using the showcase application.
Maybe you have a 1px padding/margin on your content?
The grid background can't be visible there because of the margin on the grid.
The margin there just moves the whole grid, including it's background, down by 1px.
If the background is visible there something else is also moving down an additional pixel.

**Comment by Chaoses-Ib** [comment]
You're right. The red border is not from the margin. It's probably caused by WPF's DPI scaling. I can only observe the red border when the system DPI scaling is 125%. When the scaling is 100% or 150%, I can't see it.

Feel free to close this issue if you're sure it's not related to ControlzEx. Removing the margin is enough for our case.

## 0
### Scale 125%
![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/ef3a959f-640e-4087-bee3-3d0fec13c1e9)

![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/5a27a8b1-011e-43f9-a0d3-8971d15e5bc9)

## 1
### Scale 125%
![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/7361a900-e3e6-4b6e-89b0-987db51d5b72)

![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/510b6242-5ca1-4257-9e7e-17954fb1b00f)

### Scale 100%

![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/0062b78f-a221-462b-a33e-88ca09ce69e1)

![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/d72289d6-0c03-4d21-bf2e-267a91a31b7b)

## 10
### Scale 125%
![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/82129e23-d7b4-4212-86fd-b4c3cfcf0eac)

![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/64fe6623-acf4-47b8-8ce7-44d14f62fd1f)

### Scale 100%
![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/ef0d58ae-27bf-4231-93e3-aa0c9b1b6e2a)

![image](https://github.com/ControlzEx/ControlzEx/assets/50246090/86c06c01-13f6-4812-ba70-3dc92d269ee7)

**Comment by batzen** [comment]
And DPI scaling strikes again...
Setting SnapsToDevicePixel might help, but that would propagate down the tree which might not be what everyone wants.

Will try to repro with DPI scaling again and see if I can solve the issue somehow.

**Comment by batzen** [comment]
Tried a few things and the only thing that reliably eliminates the issue is using LayoutRounding=True.
Everything else, like changing the code in NCCALCSIZE to remove 1 px from top area, does not solve the issue completely.
I couldn't even repro the issue when using 125% and had to use 175% for it to show up.

My advice:
Do not set a window background that differs from your titlebar background.
If you want to have a different window background than the titlebar background, just solve that by adding another container that contains your real window content and set the background color there.
OR:
Use LayoutRounding=True, but that might have other undesired side effects.
