### ISSUE TITLE
Samples for WindowChromeBehavior

### ISSUE THREAD

**Issue by punker76** [ControlzEx/ControlzEx#5]

**Comment by maurosampietro** [comment]
showcase shows a black chrome no matter what
![image](https://cloud.githubusercontent.com/assets/15122144/12608949/4e3dae1c-c4df-11e5-92c0-fa56b2fa6950.png)

**Comment by batzen** [comment]
I am aware of those issues and already fixed them locally.

Just have to talk to Jan (punker76) if he agrees with my fixes.

Personal question: How did you record the video? I was looking for a tool which would generate gif videos also.

**Comment by ButchersBoy** [comment]
@batzen I use this a lot: https://screentogif.codeplex.com/

**Comment by batzen** [comment]
@ButchersBoy I tried the latest preview but it grinds to a halt when trying to record the whole screen. Will give it another try later today.
If it fails again i will think about forking and fixing the issue. ;-)

**Comment by maurosampietro** [comment]
@bat i use the same https://screentogif.codeplex.com/

**Comment by maurosampietro** [comment]
@batzen what you say is true but in my experience the final gif will be smooth.

**Comment by ButchersBoy** [comment]
I've used the trial of this and it's good too; next time I need it I'm going to buy a licence: https://www.techsmith.com/snagit.html

**Comment by JaykeBird** [comment]
So are the samples still going to be forthcoming? I'd love to utilize the WindowChromeBehavior features in my program, but it'd be immensely easier for me to be able to start integrating it into my program with either a sample of the code, or a document that shows how to implement it.

**Comment by batzen** [comment]
@JaykeBird You mean something like the showcase application in this repo? The behavior is used there. To be precise it's used here https://github.com/ControlzEx/ControlzEx/blob/develop/src/ControlzEx.Showcase/MainWindow.xaml

**Comment by JaykeBird** [comment]
@batzen ah, did not see that there. alrighty, thank you!

**Comment by TheFanatr** [comment]
[WARNING: LONG POST]

ETA on the new samples? On Windows 10 Version 1706 (Build 15063.540), they are still not functioning correctly, and on top of that, the whole WindowChromeBehaviour class does not have the wanted behaviour in the first place. Basically, from what I have experienced when playing around with the source, there is still no way to have a fully-functional and fully-animated window in which you can place content within the windowchrome, without some kind of side effect. On top of that, it would seem that it is just very buggy in general. Don't get me wrong; it is still a major improvement over the WindowChrome class provided by Microsoft, but there are many things that are still unfixed and certain setup things that I personally think should be changed. I would just simply like to point them out in case there is a fix and/or possibility for amendment, per scenario.

First, here are some of the issues I am encountering:
 - No aero buttons no matter what.
 - No way to use legacy "WindowChrome.WindowChrome" with new fixes, even when referencing the included WindowChrome class
 - Choppy maximization animation
 - Double click to maximize/minimize doesn't work 50% of the time, especially when nonewindowstylewithglassframe is the style
 - Window not draggable from very top when maximized
 - [NOT AS IMPORTANT] Double-clicking on icon representation of program in the taskbar, when the window is open will focus the window that is one lower in z-order. To reiterate: quickly hiding and showing the open window via mouse double-clicking the taskbar will make the application behind it be focussed. This means that there is some kind of underlying issue with the showing of the window, which may be causing other unknown issues. I have double checked that this is not the usual behaviour.
 - no way to allow native window dragging, only with special grid as shown in showcase
 - using nonewindowstyle on window startup will case black rectangle on all of right-hand side until full redraw (hide+show)
 - using nonewindowstyle makes wrong border color and resizethickness
 - weird glitch sometimes where [WIN] + [UP] makes the window show then hide instantly, right after [WIN] + [DOWN]. I know that this issue was far worse in the actual windowchrome class from ms, and the fixes have made it better, but it still happens sometimes, and it's hard to pinpoint the cause.
 - WindowChromeBehaviour causes the WPF designer to bug-out completely, and show errors

Now, some of the things I suggest that should be changed:
 - Behaviours are a really old WPF "technology" and I think that it generally complicates more than it simplifies with this already very convoluted project. My suggestion is that all the fixes are moved into a refactored WindowChrome class that takes advantage of new C# features (possibly also .NET), and adds new functionality such as disabling certain aero buttons or hiding the icon, etc.
 - Also, the legacy WindowChrome.WindowChrome property-style initializer/"attacher" should be reinstated because I feel that it is much more convenient to use.
 - Additionally, the WindowChromeWorker should be integrated into the WindowChrome, again for simplicity, but also for a bit of abstraction because no one will ever use the WindowChromeWorker by itself because there's no point, considering the WindowChrome class already abstracts and simplifies the functionality; keeping them separate just complicates things, so make the WindowChrome do all the work directly.

Also, I would like to point out that I did find a way to use WindowChrome.WindowChrome; however, none of the improvements made were visible and it actually had more bugs, which is probably a side-effect of the changes made to it for the WindowChromeBehaviour to work. Also, that version does actually have aero buttons that work and with some modifications to the source, I was able to make it fully work, minus the animations. 

If you would like, I would be happy to help out with this, if someone were to explain the basic gist of what the WindowChrome, and WindowChromeWorker is doing, and how the fixes work and why. Thanks!

**Comment by batzen** [comment]
Hi @TheFanatr,

have you tried the develop branch?
You expect things to work, AeroCaptionButtons for example, which are just leftovers from the original Microsoft code. 
I was recently discussing with @punker76 if we should remove everything we don't use in MahApps.Metro and in Fluent.Ribbon.

This seems to be your first message and you include a lot of issues you could have reported to us separately, you could have asked on gitter, you could have asked on twitter etc. but you decide to dump all of that in a mostly unrelated issue. Why that?

> No aero buttons no matter what.

Not supported and won't be, as of now, as we don't need it.

> No way to use legacy "WindowChrome.WindowChrome" with new fixes, even when referencing the included WindowChrome class

You really expect that to work? Really?

> Double click to maximize/minimize doesn't work 50% of the time, especially when nonewindowstylewithglassframe is the style

Strange, this is used in Fluent.Ribbon. Never observed such an issue.

> Window not draggable from very top when maximized

Works like a charm.

> Double-clicking on icon representation of program in the taskbar

Can't reproduce.

> no way to allow native window dragging, only with special grid as shown in showcase

Don't know what you are expecting here. Clarify?

> using nonewindowstyle on window startup will case black rectangle on all of right-hand side until full redraw (hide+show)

You are using an old version, nonewindowstyle is not even being used in the code

> using nonewindowstyle makes wrong border color and resizethickness

You are using an old version, nonewindowstyle is not even being used in the code

> WindowChromeBehaviour causes the WPF designer to bug-out completely, and show errors

Ask MS to fix their buggy designer pls.

> Behaviours are a really old WPF "technology"

Pardon?

> takes advantage of new C# features (possibly also .NET), and adds new functionality such as disabling certain aero buttons or hiding the icon, etc.

Don't know which new C# features you are talking about.
Icon in titlebar is not even part of this library.
Maybe you should use MahApps.Metro instead of the WindowChrome class.

> Also, the legacy WindowChrome.WindowChrome property-style initializer/"attacher" should be reinstated because I feel that it is much more convenient to use.
Additionally, the WindowChromeWorker should be integrated into the WindowChrome, again for simplicity, but also for a bit of abstraction because no one will ever use the WindowChromeWorker by itself because there's no point, considering the WindowChrome class already abstracts and simplifies the functionality; keeping them separate just complicates things, so make the WindowChrome do all the work directly.

Fair points.

**Comment by TheFanatr** [comment]
Hi @batzen, sorry if it felt like I was just complaining on random things; it would seem I misunderstood the purpose of the WindowChrome classes being there. I thought that they was there as a "fixed" alternative to Microsoft's versions. Anyways, I will try to address some of the questions and/or comments you brought up, and yes, I did use the Develop branch; Master is like 6 months old.

First of all sorry for dumping everything in here, it's just that I was experiencing these behaviours with the Showcase project, more specifically the .NET462 one, and I was thinking that those were addressed by some of the "local fixes" mentioned previously. Can I assume that those fixes have in fact been already been implemented?

As for the "no aero buttons" thing, why get rid of them? I understand that they are not needed but if they don't hurt to be there, why disable them? Other people might want to come along and use the fixes along with the buttons, and since this repo is essentially just to add/extend controls in WPF, why not make that a possibility? MahApps can just disable it in code. Also, they are technically there, but just hidden and the rendering style of the window is changed to the legacy Windows 98 appearance; you can see it for a split second when maximizing (recorded at 60fps):

![screenshot 349](https://user-images.githubusercontent.com/16641853/29846807-4c1224f8-8ccd-11e7-8364-645fa7ecc858.png)

I expected the WindowChrome.WindowChrome attachable property thing to work because it actually does more/less but without the fixes, which I am assuming, as mentioned in my previous post, is attributed to the WindowChromeBehaviour class; I was wondering why the fixes weren't implemented in the actual WindowChromeWorker or wherever the fixes would "normally" apply.

As for the double clicking to minimize/maximize not working, why I said 50% of the time is because I am using a touchpad, and for some reason, when double-tappning, it registers a drag sometimes, which I am attributing to the fact that the way the window titlebar is implemented is through using a Grid with MouseLeftButtonDown attached to a handler that detects the intent. That is, at least, as far as I can tell.

As for the window not being draggable from the top when maximized, I stopped experiencing that behaviour as well, so it must have been my PC just glitching out.

As for that window hiding thing on double click, again it also only happens with touchpads. It is also very hard to capture with screen recordings because I can't show when I'm clicking or not, but basically, if the window is not minimized and not maximized, and is either in the foreground or the background, then double tapping on its icon in the taskbar will make it hide then show, but then it will disappear again if the window behind it is maximized, or focus the window behind it otherwise, which does not happen with other windows. It leads me to believe that there is something weird going on with window activation, but it could also be something to do with the way Windows handles touchpads.

When I said "native window dragging", I meant being able to drag the window without putting extra controls at the top of the window. In the showcase, there is a grid with MouseLeftButtonClick referencing a method that detects the intent of the click; I was wondering why the native implementation of window dragging via WindowChromeWorker isn't used, because I think that it would solve that double-tap to minimize/maximize not working thing.

NoneWindowStyle is one of the options for "Window Style" in ControlzEx.Showcase.NET462, and also happens to be the default setting. Below are some screenshots describing the issues described in my previous post. If NoneWindowStyle is deprecated, why is it in the showcase?

![bandicam 2017-08-29 15-43-15-377](https://user-images.githubusercontent.com/16641853/29847522-db7f53d8-8cd0-11e7-8bc5-dfc886e427a3.jpg)
![bandicam 2017-08-29 15-43-33-421](https://user-images.githubusercontent.com/16641853/29847521-db7cbce0-8cd0-11e7-9180-12fdcf8a6fa7.jpg)

I realize that it is Microsoft's duty to make sure their designer works with technologies like Behaviours, but when you could simply use the WindowChrome.WindowChrome, which is much simpler in my opinion if it was made to include the fixes and full functionality, why use Behaviours if they cause the designer to bug out?

On the topic of Behaviours, aren't they from around 2009, introduced with Expression Blend 3? I know that attachable properties are probably older, but from what I can tell, Behaviours were a contemporary thing implemented with external libraries, whereas attachable properties are more of a long lasting kind of thing, and are better integrated into the language. That's what I meant, but correct me if I'm wrong.

What I meant by new features in the language is to integrate more event handlers where there are methods like "On...", and to put things like WindowStyleChanged, and to add more functionality. So, not necessarily new feature of the language but generally some more features in the WindowChromeWorker class. This isn't entirely necessary if you think that you'll only be using the classes internally though.

Also, with the icon and titlebar stuff I was talking about, that was just as a suggestion for new functionality you could add to the WindowChrome classes, but it's the same story as above; if it's just meant for internal use, it doesn't matter. I was just suggesting it. 

If these WindowChrome classes are just mainly for internal use by the MahApps team, I would suggest that another version be made, separately that focusses on features and stuff, so that people can actually use the classes as a replacement for Microsoft's version. Just a suggestion.

Thanks, and sorry for the long post.

**Comment by batzen** [comment]
So you are right, we should have made it clearer that our WindowChrome etc. are not meant to be a fixed version for the one from microsoft. We will fix this by converting it completely to a behavior in https://github.com/ControlzEx/ControlzEx/tree/WindowChromeNext and remove everything we (MahApps.Metro and Fluent.Ribbon) don't need, don't use and don't want to support.

Supporting `UseAeroCaptionButtons` and the things alike would mean a lot of effort as even supporting the things we use is very difficult and consumes a large amount of time. Testing everything consumes the largest part of that time.

The decision to use a behavior was made because we need some state handling and we only want one class to handle everything. That's kinda possible by using attached properties, but it doesn't get easier that way.

What we want to achieve is: Provide a way for others to use a window with `WindowStyle=None` that behaves correctly.

Behaviors were invented, if you ask me, to get rid of the old style of doing the same. The old style was to have an attached property with a flag of some kind, call it `IsEnabled` if you want, create an instance of a class, which modified/enhanced/fixed the behavior of something, and assign it to a second attached property. At least that's what i did before behaviors were there.

It would be nice if you could help us getting the `new` behavior released with as few bugs as possible, preferable none of course.

Things like the titlebar and icon are out of the scope of this library, we only want to provide a way to enable people put everything inside the window they want to put inside.

If you want to discuss current issues, new features etc. please open one or more new issues so we can discuss them separated from this thread.

As a side note: WindowChromeWorker has no window dragging features at all, except from fixing bugs caused by windows 7 and .net 3.5 when dragging the window.

**Comment by punker76** [comment]
Relates to #46
