### ISSUE TITLE
Window content context menu opens with system context menu

### ISSUE THREAD

**Issue by cpCr4zy** [ControlzEx/ControlzEx#75]
Opening system menu on the window title leads to the opening context menu from the client area content. See attached sample project.
Steps to reproduce:
-	Start the test app
-	DO NOT MOVE the window!!
-	right mouse button click on the „Header“ area
-	the system menu opens, additional opens the richtextbox context menu

![22-05-_2019_16-09-29](https://user-images.githubusercontent.com/5735197/58181735-9f479b00-7cac-11e9-80f6-31ca301ad4c3.png)

[SystemMenuBug.zip](https://github.com/ControlzEx/ControlzEx/files/3207742/SystemMenuBug.zip)

**Comment by batzen** [comment]
That's not a bug in ControlzEx, but in the showcase application instead.
The problem here is that the showcase application uses `MouseRightButtonDown` to open the system menu. Which is just wrong. Showing the system menu on mouse right down causes these weird issues.
You just have to use `MouseRightButtonUp` instead and everything works as it should.
Showcase application got this fix right now.
